import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { aeonik } from "./fonts";
import "./globals.css";
import TopBar from "@/layouts/TopBar";
import Link from "next/link";
import Image from "next/image";
import Facebook from "@/icons/Facebook";
import styles from "./Page.module.css";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${aeonik.variable}`}>
        <TopBar />
        {children}
        <footer className={styles.footer}>
          <div className={styles.footer_top}>
            <div className={styles.footer_top_left}>
              <Image
                src="/logo_white.png"
                width={100}
                height={100}
                alt="909 Equity Capital"
              />
              <div>
                <h4>Contact us</h4>
                <small>
                  <Link href="mailto:info@909equitycapital.com">
                    info@909equitycapital.com
                  </Link>
                </small>
                <small>
                  <Link href="tel:+2349092686858">+234 9092686858</Link>
                </small>
              </div>
              <div>
                <h4>Location</h4>
                <address>
                  21 Aso Rock street, Block 29 Atlanta, Abuja, Republic of Congo
                </address>
              </div>
            </div>
            <div className={styles.footer_top_right}>
              <div className={styles.quick_links}>
                <Link href="/">Quick Link</Link>
                <Link href="/">Quick Link</Link>
                <Link href="/">Quick Link</Link>
                <Link href="/">Quick Link</Link>
                <Link href="/">Quick Link</Link>
                <Link href="/">Quick Link</Link>
                <Link href="/">Quick Link</Link>
                <Link href="/">Quick Link</Link>
                <Link href="/">Quick Link</Link>
                <Link href="/">Quick Link</Link>
              </div>
              <div className={styles.contact}>
                <h4>Stay Connected</h4>
                <div>
                  <Link href="/">
                    <Facebook />
                  </Link>
                  <Link href="/">
                    <Facebook />
                  </Link>
                  <Link href="/">
                    <Facebook />
                  </Link>
                  <Link href="/">
                    <Facebook />
                  </Link>
                  <Link href="/">
                    <Facebook />
                  </Link>
                </div>
              </div>
            </div>
          </div>
          <div className={styles.footer_bottom}>
            <small>
              &copy; {new Date().getFullYear()} 909EquityCapital. All Rights
              Reserved
            </small>
            <div>
              <Link href="/">Policy and Terms</Link>
              <Link href="/">Website by Egwinity</Link>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
